### PR TITLE
Fix EventOnly behaviour

### LINKED ISSUE #384: Event is not created when EventMode::EventOnly is set
In v2.4.0 when EventMode::EventOnly was set an event was always created, however in 3.0 it will now check IsEvent first.

From the 3.0 code, it looks like it checks IsEvent on the value when EventMode::EventOnly is set:

[https://github.com/dnp3/opendnp3/blob/00adff9fa4a1bb26b30aa677ff914c04614b8140/cpp/lib/src/outstation/StaticDataMap.h#L255](url)

### PR DESCRIPTION
**Pull request by emgre**
Fix #384.

- Fix `EventOnly`behaviour to match the 2.x.
- Updated outstation example adapter. `0.0.0.0` is more common default than `asdf`.
- Updated TLS examples to be consistent.

### CODE REVIEW

File: cpp/lib/include/opendnp3/gen/EventMode.h [hunk 1]
```diff
@@ -48,7 +48,8 @@ enum class EventMode : uint8_t
   Force = 0x1,
   /// Never produce an event regardless of changes
   Suppress = 0x2,
-  /// Send an event directly to the event buffer, bypassing the static value completely
+  /// Force the creation of an event bypassing detection mechanism, but does not
```
Comment (jadamcrain) [inline cpp/lib/include/opendnp3/gen/EventMode.h]: We need to update this comment via the code generator. It will also update java/.net

Comment (emgre) [reply cpp/lib/include/opendnp3/gen/EventMode.h]: 🤦‍♂️ My bad
